context/ethereumContext.tsx
This fixes an issue when `selectedFork` would get into an `undefined` state prior to getting a block for the execution
=> fix: Undefined selectedFork when getting a block for execution

components/Editor/index.tsx, lib/solcWorker.js, util/compiler.ts
This extracts compiler version to util/compiler so we don't forget to update it everywhere next time.
=> fix: SolcJS compiler version label

docs/opcodes/55/berlin.mdx, docs/opcodes/55/constantinople.mdx, docs/opcodes/55/istanbul.mdx, opcodes.json
Adding the definitions of `value`, `current_value` and `original_value` for opcode SSTORE gas computation variables
=> SSTORE gas variable definitions

.env.development, .env.production, components/Editor/index.tsx, util/browser.ts
The dotfiles introduced in #103 and #104 are not needed since `NEXT_PUBLIC_VERCEL_URL` is already one of the [exposed environment variable](https://vercel.com/docs/concepts/projects/environment-variables) by Vercel. The original bug was not using the correct prefix in the `getAbsoluteURL` of `util/browser.ts`, which is fixed in this PR. After deploying this one, the custom environment variable in the Vercel settings is no longer required too - check out the Preview environment where it works w/o it.
=> fix: getAbsoluteURL and remove unnecessary dot files

docs/opcodes/F0.mdx
I'm assuming the stack output of CREATE was accidentally omitted, rather than intentionally (given it is included in CREATE2 and most opcodes document their stack output). Address is correctly mentioned in the "STACK OUTPUT" portion of the opcode table, so this is just a minor issue with aligning the docs
=> fix: add stack output to CREATE documentation

components/Reference/DynamicFee.tsx, components/ui/Radio.tsx
When estimating the gas cost of the SSTORE instruction, we provide an option to tell the calculator if the storage is warm or cold. However, if the current value of the slot is different from the original value, that implies that the slot has already been touched as part of this transaction and therefore can't be cold.
This change disables the 'cold' option when current value != original value and visually causes the option to appear as though the user has selected 'No' (meaning 'not cold'), when disabled. If current value and original value are later changed to be equal again, the 'cold' option is restored to whatever value was selected before.
Resolves #118
=> Disable 'cold' option when estimating SSTORE gas costs with known warm storage

docs/opcodes/A4.mdx
The first stack item was `topic` which should have been `offset`. This pull request fixes this typo.
=> changed a typo got Log4 opcode.

docs/precompiled/0x06.mdx
=> Fix typo in 0x06 ecadd description

components/Editor/ExecutionState.tsx, components/Editor/Header.tsx, components/Editor/InstructionRow.tsx, components/Reference/DocRow.tsx, components/Reference/Filters.tsx, components/Reference/Header.tsx, components/Reference/index.tsx, components/ui/Doc.tsx, components/ui/Input.tsx, components/ui/Label.tsx, pages/about.tsx
_Note: a lot of these proposed changes are just personal preferences! Happy to revert any of these changes, but I think a few of them are important for readability._
**Home page**:
- Fixed alignment of title + badge/label (e.g. "Instructions — ARROWGLACIER")
- Added letter spacing to small uppercase text for improved readability
- Fixed text colors for dark mode to improve a11y/visibility
**Playground page**:
- Fixed alignment of title + badge/label (e.g. "EVM Playground — ARROWGLACIER")
- Fixed text colors for dark mode to improve a11y/visibility
**About page**:
- Added max width to improve readability on larger screens
For comparing before vs after. (Most of the changes are subtle, see above for description of what changed!)
| Home page (before)  | Home page (after) |
| ------------- | …
=> Minor design/dark-mode improvements

docs/opcodes/F0.mdx, docs/opcodes/F5.mdx, docs/opcodes/F5/berlin.mdx, opcodes.json
That 0 is returned on failure.
Also more notes describing reasons for failure and how the addresses are
calculated.
=> Fix: CREATE and CREATE2 return values on failure (#142)

components/Editor/InstructionRow.tsx
We should add the opcode id in the Instruction row, so we can trace the next opcode id when the current opcode is```JUMP``` or ```JUMPI```.
=> [chore] add opcode id show.

docs/opcodes/F0.mdx
The bytecode `0x63FFFFFFFF60005260046000F3` that is deployed in the 3rd CREATE in the CREATE playground is strange in the sense that it PUSHes `0xFFFFFF` on stack, MSTOREs it and returns 4 bytes (RETURN instruction with offset 0 and size 4). However this returns `0x000000`. This isn't a mistake per se, it seems like a typo where the intent was to return the 4 bytes previously MSTOREd.
This pull request changes the bytecode to `63FFFFFFFF6000526004601CF3` so that the returned bytecode coincides with the 4 bytes previouslypushed on stack.
=> chore: fix the playground example for CREATE

docs/precompiled/0x01.mdx
The valid range for s is ]0, secp256k1n[, as can be checked in the [playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code='jFirsNplace_parameters%20in%20memoryZ456e9aea5e197a1f1af7a3e85a3212fa4049a3ba34c2289b4c860fc0b0c64ef3whash~Y~27wvX2YZ9242685bf161793cc25603c231bc2f568eb630ea16aa137d2664ac8038825608wrX4YZb0751c428acadb72f42bb7d6733d1df79c5843b9a7d3c407b39bd3a37fb11667wsX6YqqjDo_call~32JSizeX80JOffsetX8VSize~VOffset~1waddressW4QFFFFFFFFwgasqSTATICCALLqqjPut_resulNalonKon_stackqPOPX80qMLOAD'~W1%20w%20jq%5Cnj%2F%2F%20_%20thKZW32QY0qMSTOREX~0xWqPUSHV0wargsQ%200xNt%20Ke%20Jwret%01JKNQVWXYZ_jqw~_). The playground example I am linking in particular is the same signature as the example provided on evm.codes but with `s' = secp256k1n - s` and `v` flipped (27 instead of …
=> Fix specification error

google36538dd7d1ae8edc.html
Google Search Console requires us to add this html file to our repo, to verify smlXL's ownership of EVM Codes.
=> Add Google ownership verification file

google36538dd7d1ae8edc.html, public/google36538dd7d1ae8edc.html
Google ownership verification file needs to be in public directory to be legible to Google's verification service
=> Move ownership verfication file

docs/precompiled/0x06.mdx
#141 fixed a typo of the mislabeled point y2, but missed the byte range
=> Fix byte range of `ecadd` precompile

components/ChainSelector.tsx, components/Editor/index.tsx, components/Reference/index.tsx, pages/precompiled.tsx
See this [issue](https://github.com/comitylabs/evm.codes/issues/84)
Added the option to provide a `fork` query parameter to the following pages:
- Precompiles
- Playground
- Reference Table
Also added the `fork` query parameter to the permalink copy feature of Playground.
=> Add fork to query params

components/Reference/Filters.tsx
Added a `name` query parameter handling code to the `Filters.tsx` component. This handler will set a filter on the `Name` column of a table (either opcodes or precompiles) with the value of the query parameter.
In example:
- `evm.codes/precompiled?name=ec` will yield a search on the precompiles table for precompiles containing the sequence `ec` (ecrecover, ecpairing).
- `evm.codes/?name=self` will yield a search on the opcodes table for opcodes containing the sequence `self` (SELFDESTRUCT, SELFBALANCE).
Note: I did not set an `opcode` query parameter with the opcode's hex form (e.g `0x60`) since we already have the anchored views for that.
This PR should close this issue #122
=> Added `name` query parameter handling

pages/about.tsx
Rightly or wrongly, most places on the web use calldata as a single word.
For example, the Intrinsic Gas section of this About page also uses "calldata".
=> fix: "call data" to calldata

components/Editor/index.tsx
There's a bug in the `/playground` page where you cannot set a `value` when the unit is `Wei`.
You can reproduce the issue like this:
- go to https://www.evm.codes/playground?callValue=8&unit=Wei&callData=&codeType=Bytecode&code=%2734380356FDFD5B00FDFD%27_&fork=merge
- make sure that the value of the `Value to send` input is a non-zero value; leave the unit as `Wei`
- hit `Run`
- click the `Step into` button
- the `CALLVALUE` op code will push the current value onto the stack
- but if you look at the `STACK`, you'll see that it has pushed `0` onto the stack, not your specified value.
Here's a sceenshot of the bug in action. The value is set to `10 Wei`, but after calling `CALLVALUE` to push the value onto the stack, the stack only contains the value `0`.
This looks like a bug that snuck …
=> fix: getCallValue default on `/playground` page

bytecode.js, components/Editor/index.tsx, util/string.ts
Proposing a live-updating editor in Bytecode mode - it shows the opcodes on the right when writing bytecode.
Should help much when analyzing/writing minimal contracts directly in Bytecode.
Features added:
- Live-update of the opcodes when editing the bytecode
- Ability to put spaces and newlines in bytecode without errors in compilations
- Ability to put comments in bytecode (three styles supported: `// comment`, `# comment`, `; comment`)
- Added `bytecode` language to HLJS with comments highlighting
- Delayed bytecode error validation for hex and even-byte length (for better typing UX)
Maybe something else can be added if interactive mode is worth going forward with, like:
- A switch "Interactive mode: ON/OFF"
- Show decoded opcodes on bytecode page loads
- Interchange between …
=> Feat: Live bytecode mode in Editor

pages/about.tsx
Thanks for a very useful website. Just fixing this:
=> Add space between words 'our' and 'reference' in About

docs/opcodes/3E.mdx
Maybe the old and the new formulations are equal, but I think this way it is clearer what is meant.
=> Clarify error condition of returndatacopy

pages/about.tsx
The [calldata paragraph in "About the EVM"](https://www.evm.codes/about#calldata) currently reads:
>The calldata region is the data sent to a transaction as part of a smart contract transaction. For example, when creating a contract, calldata would be the constructor code of the new contract. **It is important to note that when a contract executes an xCALL instruction, it also creates an internal transaction, with a resulting calldata region in the new context.** Calldata is immutable, and can be read with instructions [CALLDATALOAD](https://www.evm.codes/#35), [CALLDATASIZE](https://www.evm.codes/#36), and [CALLDATACOPY](https://www.evm.codes/#37). **When a contract executes an xCALL instruction, it also creates an internal transaction. As a result, when executing xCALL, there is a …
=> chore: delete redundant sentence in calldata description

docs/precompiled/0x02.mdx
The "Reproduce in playground" example on this page runs successfully now, so this PR updates the output to match the playground.
I confirmed the hash from the playground is accurate by running this JavaScript:
```javascript
const input = 0xff;
[...new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256', new Uint8Array([input])))].map(b => b.toString(16).padStart(2, '0')).join('');
// 'a8100ae6aa1940d0b663bb31cd466142ebbdbd5187131b92d93818987832eb89'
```
Note: sometimes the examples prefix the hex with `0x` (like in ecRecover), sometimes not (like in RIPEMD-160). I chose to omit the prefix to be consistent with RIPEMD-160.
=> chore: update SHA2-256 precompile example output 

docs/precompiled/0x09.mdx
This PR adds a minimal opcode example for the blake2f precompile. The input data was copied from "test vector 5" on https://eips.ethereum.org/EIPS/eip-152
=> chore: add blake2f example

context/ethereumContext.tsx, util/constants.ts
as we recently moved to timestamps (shanghai), while the app relies on blocks, the `findMatchingForkName` used in dynamic fee docs fails.
this is a workaround hack to treat timestamp as block numbers until we get ethereumjs packages upgraded and the app working with timestamps.
to be addressed in #238
=> fix: shanghai dynamic fee is not displayed

docs/opcodes/FA.mdx
For reference: https://blog.ethereum.org/2017/10/12/byzantium-hf-announcement
- https://github.com/ethereum/execution-specs/blob/master/src/ethereum/byzantium/vm/instructions/system.py#L473
- https://github.com/ethereum/execution-specs/blob/master/src/ethereum/spurious_dragon/vm/instructions/system.py#L594
=> fix: `staticcall` opcode was introduced during the `Byzantium` hard fork

components/EvmStorageBanner.tsx, pages/index.tsx
I added an evm.storage banner. It can be closed, but it will reopen when the user refreshes the page. My thought is that we would only use this banner for a few weeks and then we could explore a more permanent place to add the link.
Tried to do this in a way that was clean and aligned with @alannafischer's designs. May not be quite pixel perfect but should be very close.
[will fix the prettier stuff now]
=> Add evm storage banner

docs/precompiled/0x01.mdx, docs/precompiled/0x02.mdx, docs/precompiled/0x03.mdx, docs/precompiled/0x04.mdx, docs/precompiled/0x05.mdx, docs/precompiled/0x06.mdx, docs/precompiled/0x07.mdx, docs/precompiled/0x08.mdx, docs/precompiled/0x09.mdx
Fixes https://github.com/smlxl/evm.codes/issues/259. In order to verify this behaviour, you can look at the [`py-evm`](https://github.com/ethereum/py-evm/tree/master/eth/precompiles) implementations.
=> Enhance invalid input description for precompiles

components/Reference/index.tsx, context/ethereumContext.tsx
- We add `shanghai` to the post merge HF list.
- When checking if the user selected the `merge` HF, we now check against the list.
This addresses [this issue](https://github.com/smlxl/evm.codes/issues/263).<br>
Note: This is still a hacky workaround, we should consider the refactoring suggested in the `TODO` comments.
Locally with `yarn dev`
=> add shanghai to post-merge HF list

docs/opcodes/F0.mdx
The current description does not say anything about how the initialisation code is provided by the end user.
=> Explain how initialisation code is provided to CREATE

components/Editor/index.tsx
Fixes #280 
Allow bytecode to include the `0x` prefix without it being considered illegal opcode. 
- Open playground https://evm-codes-git-feature-allow-0x-prefix-with-bytecode-smlxl.vercel.app/playground
- Add a `0x` prefix i.e `0x604260005260206000F3` and it should not load with a `INVALID` opcode like it currently does with main
- ![Screenshot 2023-12-12 at 09 27 36](https://github.com/smlxl/evm.codes/assets/5640782/a336df78-5a72-4361-8cf3-68809fb83504)
=> Allow 0x prefix in bytecode editor

pages/about.tsx
This PR includes the following changes to the `about` page:
- add details about [EIP3651](https://eips.ethereum.org/EIPS/eip-3651): the `COINBASE` address is always warm 
- add missing details about [EIP2929](https://eips.ethereum.org/EIPS/eip-2929): `tx.sender` and `tx.to` are always warm
- fix some typos
=> fix: add changes from eip3651

docs/opcodes/F0.mdx, docs/opcodes/F5.mdx
fix #185, the memory offset of the init code passed to `CREATE` and `CREATE2` would be incorrect, `0` instead of `19`. It can be easily verified by adding `EXTCODESIZE` at the end of the bytecode which would now return `4` when it previously returned `0`.
=> fix: examples for create and create2

.gitignore, .yarnrc.yml, components/Editor/SolidityAdvanceModeTab.tsx, components/Editor/index.tsx, context/ethereumContext.tsx, next.config.js, package.json, util/gas.ts, webpack/importAssertTransformer.js, webpack/nodeModuleReplacement.js, yarn.lock
Short summary of the changes
- Needed to add two webpack / babel loaders to be able to import `rustbn` used by Ethereumjs.
- There was some minor changes to the types used by EthereumJS so updated to reflect the new types.
- Mainly `HardforkConfig` -> `HardforkTransitionConfig`
- `Buffer` -> `Uint8Array`
- `getActiveOpcodes` isn't exposed on `vm` anymore, just reconstructing the input to EVM was easiest. 
1. Make sure the fork selector correctly reflect the active opcodes (i.e `PUSH0` should not be shown in Paris hardfork) ✅ 
2. Playground should have it's storage and stack be correctly updated when running through a contract that interacts with storage ✅ 
3. Check that dynamic gas cost is correctly reflected based on version (i.e check that the dynamic cost of `CREATE` is correctly shown …
=> Bump ethereumjs libraries

components/Editor/ExecutionState.tsx, lib/solcWorker.js, package.json, styles/globals.css, tsconfig.json, yarn.lock
- upgrade `prettier` from 2.4.1 to 3.2.5
- add `format` npm script to `package.json`
- run `yarn format` over full codebase
=> chore: upgrade prettier to v3

docs/opcodes/20.mdx
The existing playground example uses the SHA3 opcode, which the playground doesn't recognize.
The fix is to replace SHA3 with KECCAK256.
Related: #311
=> fix: keccak256 playground example

docs/opcodes/20/homestead.mdx, docs/opcodes/F5/berlin.mdx, docs/opcodes/F5/constantinople.mdx, docs/opcodes/F5/shanghai.mdx, util/gas.ts
This fixes a bug where opcodes that relied on the value of sha3 or sha3Word were rendering on the page with a value of 0, giving an incorrect representation of gas fees for the respective opcodes.
This bug appears to be caused by this change in EthereumJS:
https://github.com/ethereumjs/ethereumjs-monorepo/pull/2706/files#diff-aa85288d3ff116040e9adfce5d7d74b582eee859ea89af6cf69cb29f5bccc079
The fix is to switch to the new keccak semantics instead of the deprecated SHA3 semantics.
Related #310
=> fix: replace sha3 with keccak256 in gas calculations

docs/opcodes/F2.mdx
Should fix [this](https://github.com/smlxl/evm.codes/issues/298#event-12303500575) issue
=> fix revert case list of CALLCODE

docs/precompiled/0x0a.mdx
I didn't add an example section or a "Reproduce in playground" in playground because of this precompile's multi-layer dependency.
=> chore: add 0x0a precompile

components/Editor/ExecutionStatus.tsx, components/Editor/SolidityAdvanceModeTab.tsx, components/Editor/index.tsx, components/Reference/index.tsx, components/ui/Button.tsx, package.json, pnpm-lock.yaml
- upgrade `react-tooltip` from 4.2.21 to 5.26.4
- update imports for `react-tooltip` to use named imports
- update usage of `data-tip` to `data-tooltip-content`
- update usage of `data-for` to `data-tooltip-id`
- remove `effect="solid"` prop which became default in v5
- go to https://evm-codes-git-chore-upgrade-react-tooltip-to-v5-smlxl.vercel.app/playground
- hover over icons to the right of the playground panel
- expect tooltips to work like before
=> chore: upgrade react-tooltip to v5

package.json, pnpm-lock.yaml
- upgrade `sort-package-json` from 1.52.0 to 2.10.0
- run `lint:package` script which changes ordering of `package.json`
=> chore: upgrade sort-package-json to v2

docs/opcodes/F0.mdx
This adds a note, that `CREATE` fails if there already exists a contract at the target address.
In the normal case, this does not happen as the target address depends on the contracts nonce and the nonce always gets increased by one. However, by (ab-)using `CREATE2`, `SELFDESTRUCT` we can continuously create and destroy a contract that will always have the same initial nonce. From this contract, using `CREATE` will always result in the same address and can lead to conflicts with already existing contracts. Maybe there's also an easier way that leads to conflicts.
=> chore: note that CREATE fails if target already exists

components/ContractViewer/index.tsx
Fixes #331 issue reported by high_byte
Verify that USDC implementation is loaded when adding the proxy address `0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48`. Current deployed version does not do this.
=> Fix loading of implementation in code viewer

components/ContractViewer/DeploymentInfo.ts, util/solc.ts
When you try to view `0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD ` in the Contract Viewer, you get the following compilation errors:
```
[
{
"component": "general",
"errorCode": "6275",
"formattedMessage": "ParserError: Source \"@openzeppelin/contracts/token/ERC721/IERC721Receiver.sol\" not found: File import callback not supported\n --> contracts/base/Callbacks.sol:4:1:\n  |\n4 | import {IERC721Receiver} from '@openzeppelin/contracts/token/ERC721/IERC721Receiver.sol';\n  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n",
"message": "Source \"@openzeppelin/contracts/token/ERC721/IERC721Receiver.sol\" not found: File import callback not supported",
"severity": "error",
"sourceLocation": {
"end": 160,
"file": "contracts/base/Callbacks.sol", …
```
=> propagate SoliditySettings when compiling contracts

util/flatten.ts
If you currently try to compile the flattened version of `0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD` you get an error: 
```
DeclarationError: Identifier already declared.
--> contracts/test-flatten/UniversalRouter.sol:807:1:
|
807 | abstract contract ERC20 {
| ^ (Relevant source part starts here and spans across multiple lines).
Note: The previous declaration is here:
--> contracts/test-flatten/UniversalRouter.sol:363:1:
|
363 | abstract contract ERC20 {
| ^ (Relevant source part starts here and spans across multiple lines).
```
This is because ERC20 is inserted twice into the flattened source code. Our current code tries to handle duplicate insertion but it doesn't take into account remappings. 
In this particular contract ERC20 is import twice in two different files. Once as …
=> Fix import paths

docs/opcodes/55/berlin.mdx
1. Fix an incorrect and unreachable case of the gas refund computation for `SSTORE`
2.  Fix #312 
If and only if the following conditions are met:
```
value != current_value
value == original_value != 0
key is cold
```
The gas refund computation would do:
```
gas_refunds += 4900
```
However, this behaviour is not defined by [EIP-2200](https://eips.ethereum.org/EIPS/eip-2200) and [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929) and the conditions are impossible to reach given that if `original_value != current_value`, it must be that the key is warm.
According to both [EIP-2200](https://eips.ethereum.org/EIPS/eip-2200) and [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929), the defined computations are correct and there is no distinct case when the key is cold or warm. There is hence …
=> fix: `SSTORE` gas

util/flatten.ts
Previously it only took into account licenses like this
`// SPDX...`
but it failed to take into account licenses like
`* SPDX ...` which can be part of a multi-line comment.
This PR fixes this.
https://github.com/smlxl/evm.codes/assets/13179168/9c819c75-3020-495e-8c65-096acf280555
https://github.com/smlxl/evm.codes/assets/13179168/5f6747c6-d1c9-40e5-8869-ec7b82c7b81f
Tested on `0x43506849D7C04F9138D1A2050bbF3A0c054402dd`
=> Remove multiple SPDX licenses correctly

components/ChainSelector.tsx, components/Editor/index.tsx, components/Reference/index.tsx, context/ethereumContext.tsx, package.json, pages/precompiled.tsx, util/compiler.ts
Fixes
- Reported issue by user #345 
- Links to opcodes not working if a fork was selected
- Forks not loading correctly because of race condition where forks were loaded after `onfork` was called. Fixed by adding a new field to the context.
Some of the underlying logic related to this should be re-worked as it's called from multiple places, but that is not in scope for this PR. 
1. Opening shared opcodes should not crash app (example from issue) 
- (preview build works) https://evm-codes-git-hotfix-fix-link-crash-smlxl.vercel.app/?fork=cancun#f3 
- (prod fails) https://evm.codes/?fork=cancun#f3
- <img width="1269" alt="Screenshot 2024-09-16 at 19 10 40" src="https://github.com/user-attachments/assets/264ff121-67ea-460d-b159-d3b78a88f6d0">
2. Fork selector should still work
- …
=> Fix issue with some opcodes crashing on linkage

package.json, pnpm-lock.yaml
- update used `pnpm` version from 8.15.6 to 9.10.0
- require minimum `pnpm` version of 9.0.0 or higher
See https://github.com/smlxl/evm.codes/pull/347#discussion_r1761316001
- ensure Vercel builds successfully
- ensure application works as expected
=> chore: upgrade to pnpm v9

components/Reference/index.tsx, context/ethereumContext.tsx, util/constants.ts
Fixes reported issue #350 
1. Open the preview build
2. Verify gas calculations shows for dynamic opcodes (`CREATE2`, `DELEGATECALL`, etc) 
(On prod it doesn't show without re-selecting the fork which is a bug)
=> Fix issue with dynamic gas section not loading

README.md, components/ui/vector/README.md, docs/ARCHITECTURE.md
- Old: "Specify the environment variables if you want to run the contract viewer into `.env.local`"
- New: "Specify the environment variables if you want to run the contract viewer in `.env.local`"
**Reason**: The preposition "into" was incorrect in this context. "in" is the proper preposition when referring to specifying variables in a file.
- Old: "Download Icomoon pack, follow these commands to generate a React component with all the icons includes as SVG defs:"
- New: "Download Icomoon pack, follow these commands to generate a React component with all the icons included as SVG defs:"
**Reason**: "includes" was incorrectly used as a past participle. "included" is the correct past participle form when used as an adjective.
- Old: "Opcode with dynamic gas fee portion"
- New: "An Opcode …
=> Grammar and Wording Improvements

util/constants.ts
The previous address has been 404, replaced with available
=> fix broken url

docs/opcodes/03.mdx, docs/opcodes/05.mdx, docs/opcodes/06.mdx, docs/opcodes/07.mdx, docs/opcodes/0B.mdx
Fixed:
Replaced to with from for accuracy.
Simplified integer result of the signed integer division to signed integer division result.
Updated If the denominator is 0, the result will be 0. to If the denominator equals 0, the result is 0. for improved clarity.
Clarified All values are treated as two’s complement signed to All values are treated as two's complement 256-bit signed for precision.
Changed to sign extend to to be sign-extended for grammatical correctness.
Why it's useful:
These changes enhance precision, grammatical accuracy, and readability, making the text clearer and more professional.
=> Refine grammar, clarity, and precision in documentation

docs/opcodes/F7.mdx, docs/opcodes/FA.mdx, docs/opcodes/FB.mdx
1. - Old: "The **RETURNDATALOAD** is used to load 32 bytes word"
- New: "**RETURNDATALOAD** is used to load 32-byte word"
- Reason: Removed unnecessary article and fixed hyphenation of compound adjective
2. - Old: "load 32 bytes word"
- New: "load 32-byte word" 
- Reason: Fixed hyphenation of compound adjective for consistency
1. - Old: "execute the code"
- New: "executes the code"
- Reason: Fixed subject-verb agreement in present tense
2. - Old: "This instructions is"
- New: "This instruction is"
- Reason: Fixed plural/singular agreement
- Old: "This instructions is"
- New: "This instruction is"
- Reason: Fixed plural/singular agreement
These changes improve the documentation's readability and professional quality by:
1. Ensuring consistent grammatical structure
2. Fixing incorrect …
=>  Grammar Fixes in EVM Opcode Documentation

docs/opcodes/5C.mdx
Description:
- Specify in the `Error cases` section of the opcode that it will fail if the executed within a static context. 
[Execution Specs reference](https://github.com/ethereum/execution-specs/blob/2926c00c1d130e5d0641d278012d42267f3feaf3/src/ethereum/cancun/vm/instructions/storage.py#L171)
Closes #363
=> fix: add error case for TSTORE when context is static

pages/index.tsx
Hides sim banner. Leaves code for the banner in case we want to repurpose later.
=> hide sim banner
